name: geodpy_env_test
channels:
  - conda-forge
  - defaults
dependencies:
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py37hcc03f2d_2
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - bleach=6.0.0=pyhd8ed1ab_0
  - ca-certificates=2022.12.7=h5b45459_0
  - cffi=1.15.1=py37ha95fbe2_1
  - colorama=0.4.6=pyhd8ed1ab_0
  - debugpy=1.5.1=py37hd77b12b_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - flit-core=3.8.0=pyhd8ed1ab_0
  - ipykernel=6.14.0=py37h90c5f73_0
  - ipython=7.33.0=py37h03978a9_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jupyter_client=7.4.9=pyhd8ed1ab_0
  - jupyter_contrib_core=0.4.0=pyhd8ed1ab_0
  - jupyter_contrib_nbextensions=0.7.0=pyhd8ed1ab_0
  - jupyter_core=4.11.1=py37haa95532_0
  - jupyter_highlight_selected_word=0.2.0=py37h03978a9_1005
  - jupyter_latex_envs=1.4.6=pyhd8ed1ab_1002
  - jupyter_nbextensions_configurator=0.6.1=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - libiconv=1.17=h8ffe710_0
  - libsodium=1.0.18=h8d14728_1
  - libsqlite=3.40.0=hcfcfb64_0
  - libxml2=2.9.14=hf5bbc77_4
  - libxslt=1.1.35=h2bbff1b_0
  - libzlib=1.2.13=hcfcfb64_4
  - lxml=4.9.1=py37h1985fb9_0
  - markupsafe=2.1.1=py37h2bbff1b_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=2.0.4=pyhd8ed1ab_0
  - nbclient=0.6.8=pyhd8ed1ab_0
  - nbconvert=7.2.9=pyhd8ed1ab_0
  - nbconvert-core=7.2.9=pyhd8ed1ab_0
  - nbconvert-pandoc=7.2.9=pyhd8ed1ab_0
  - nbformat=5.1.3=pyhd8ed1ab_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - notebook=6.3.0=py37h03978a9_0
  - openssl=3.0.7=hcfcfb64_2
  - packaging=23.0=pyhd8ed1ab_0
  - pandoc=2.19.2=h57928b3_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - prometheus_client=0.16.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.36=pyha770c72_0
  - psutil=5.9.0=py37h2bbff1b_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.14.0=pyhd8ed1ab_0
  - python=3.7.12=h900ac77_100_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.7=3_cp37m
  - pywin32=227=py37hcc03f2d_1
  - pywinpty=2.0.2=py37h5da7b33_0
  - pyyaml=6.0=py37hcc03f2d_4
  - pyzmq=23.2.0=py37hd77b12b_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlite=3.40.0=hcfcfb64_0
  - terminado=0.15.0=py37h03978a9_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tornado=6.2=py37hcc03f2d_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - ucrt=10.0.22621.0=h57928b3_0
  - vc=14.3=hb6edc58_10
  - vs2015_runtime=14.34.31931=h4c5c07a_10
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - wheel=0.38.4=pyhd8ed1ab_0
  - winpty=0.4.3=4
  - yaml=0.2.5=h8ffe710_2
  - zeromq=4.3.4=h0e60522_1
  - pip:
    - altair==4.2.2
    - anyio==3.6.2
    - anywidget==0.2.0
    - asgiref==3.6.0
    - attrs==22.2.0
    - backports-zoneinfo==0.2.1
    - basemap==1.3.6
    - basemap-data==1.3.2
    - blessings==1.7
    - blinker==1.5
    - bokeh==2.4.3
    - bottle==0.12.23
    - branca==0.6.0
    - cachecontrol==0.12.11
    - cachetools==5.3.0
    - cefpython3==66.1
    - certifi==2022.12.7
    - charset-normalizer==3.0.1
    - click==8.1.3
    - clr-loader==0.2.5
    - cmake==3.25.0
    - commonmark==0.9.1
    - config==0.5.1
    - crypto==1.4.1
    - cryptography==40.0.1
    - cycler==0.11.0
    - deprecated==1.2.13
    - django==3.2.18
    - ee==0.2
    - firebase==4.0.1
    - firebase-admin==6.1.0
    - flask==2.2.3
    - folium==0.14.0
    - fonttools==4.38.0
    - gcloud==0.18.3
    - geographiclib==2.0
    - geomap==0.2.1
    - geopy==2.3.0
    - gitdb==4.0.10
    - gitpython==3.1.30
    - google-api-core==2.11.0
    - google-api-python-client==2.83.0
    - google-auth==2.17.1
    - google-auth-httplib2==0.1.0
    - google-cloud-core==2.3.2
    - google-cloud-firestore==2.10.1
    - google-cloud-storage==2.8.0
    - google-crc32c==1.5.0
    - google-resumable-media==2.4.1
    - googleapis-common-protos==1.59.0
    - greenlet==2.0.2
    - grpcio==1.53.0
    - grpcio-status==1.53.0
    - httplib2==0.22.0
    - idna==3.4
    - importlib-metadata==4.13.0
    - importlib-resources==5.10.2
    - ipyleaflet==0.17.2
    - ipywidgets==8.0.4
    - itsdangerous==2.1.2
    - js2py==0.74
    - jsonschema==4.17.3
    - jupyterlab-widgets==3.0.5
    - jwcrypto==1.4.2
    - kiwisolver==1.4.4
    - leaflet==0.0.3
    - libclang==15.0.6.1
    - mapwidget==0.1.2
    - markdown-it-py==2.1.0
    - matplotlib==3.5.3
    - mdurl==0.1.2
    - msgpack==1.0.5
    - mypy-extensions==1.0.0
    - naked==0.1.32
    - numpy==1.21.6
    - oauth2client==4.1.3
    - obspy==1.3.1
    - pandas==1.3.5
    - pillow==9.4.0
    - pip==23.0.1
    - pkgutil-resolve-name==1.3.10
    - platformdirs==2.6.2
    - pluggy==1.0.0
    - proto-plus==1.22.2
    - protobuf==4.22.1
    - proxy-tools==0.1.0
    - psygnal==0.8.1
    - pyarrow==11.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycryptodome==3.17
    - pydeck==0.8.0
    - pyjsparser==2.7.1
    - pyjwt==2.6.0
    - pympler==1.0.1
    - pyparsing==3.0.9
    - pyproj==3.2.1
    - pyqt5==5.15.8
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.11.1
    - pyqt6-qt6==6.5.0
    - pyqt6-sip==13.5.0
    - pyqtlet==0.3.3
    - pyqtlet2==0.9.3
    - pyqtwebengine==5.15.6
    - pyqtwebengine-qt5==5.15.2
    - pyrsistent==0.19.3
    - pyscript==0.2.5
    - pyshp==2.3.1
    - pyside6==6.0.0
    - pyside6-addons==6.4.2
    - pyside6-essentials==6.4.2
    - python-dotenv==0.21.1
    - python-firebase==1.2
    - python-jwt==4.0.0
    - pythonnet==3.0.1
    - pytz==2022.7.1
    - pytz-deprecation-shim==0.1.0.post0
    - pywebview==3.3
    - qtpy==2.3.0
    - requests==2.28.2
    - requests-toolbelt==0.10.1
    - rich==12.6.0
    - rich-click==1.6.1
    - rsa==4.9
    - scipy==1.7.3
    - semver==2.13.0
    - setuptools==67.6.1
    - shellescape==3.8.1
    - shiboken6==6.0.0
    - smmap==5.0.0
    - sniffio==1.3.0
    - sqlalchemy==2.0.0
    - sqlparse==0.4.3
    - streamlit==1.18.0
    - streamlit-folium==0.11.0
    - toml==0.10.2
    - toolz==0.12.0
    - traittypes==0.2.1
    - typer==0.4.2
    - typing-extensions==4.4.0
    - tzdata==2022.7
    - tzlocal==4.2
    - uritemplate==4.1.1
    - urllib3==1.26.14
    - validators==0.20.0
    - watchdog==2.2.1
    - watchfiles==0.18.1
    - werkzeug==2.2.3
    - widgetsnbextension==4.0.5
    - wrapt==1.15.0
    - xyzservices==2022.9.0
    - zipp==3.12.0
prefix: C:\Users\Lenovo\.conda\envs\env_QT

